port="8888"
dev = true

[aria2]
disk-cache=0
file-allocation="prealloc"
continue=true
max-tries=50
rpc-listen-port=6800
max-concurrent-downloads=10
max-connection-per-server=10
min-split-size="5M"
split=10
disable-ipv6=true
always-resume=false
keep-unfinished-download-result=false
input-file="/etc/aria2/aria2.session"
save-session="/etc/aria2/aria2.session"
save-session-interval=60
enable-rpc=true
pause=false
rpc-allow-origin-all=true
rpc-listen-all=true
rpc-save-upload-metadata=true
rpc-secure=false
rpc-secret="my_aria2_secret"
aria2_download_dir = "/Users/dorachen/swandownload" # "/home/peware/testGoSwanProvider"
aria2_conf = "/etc/aria2/aria2.conf"
aria2_host = "127.0.0.1"
aria2_port = 6800
aria2_secret = "my_aria2_secret"

[main]
api_url = "http://192.168.88.216:5002" #"http://127.0.0.1:5000"
miner_fid = "t03354"
expected_sealing_time = 1920    # 1920 epoch or 16 hours
import_interval = 600           # 600 seconds or 10 minutes
scan_interval = 600           # 600 seconds or 10 minutes
api_key = "yr0wUW37PEm1ZUtes-0NVg"
access_token = "878da9defc1841dd5ab9f4dcef1ec9af"
